### ISSUE TITLE
No such file or directory错误

### ISSUE THREAD

**Issue by baikourin** [mtianyan/cookiecutter-tyadmin-demo#1]
我把database 换成了postgresql。
执行`python manage.py init_admin && python manage.py gen_all`的时候出现下面错误。
```
/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/tyadmin_api_cli
/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo
/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/tyadmin_api_cli
******************** 已自动生成urls ********************
/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/tyadmin_api_cli
{'auth': ['Permission', 'Group'], 'contenttypes': ['ContentType'], 'user': ['UserInfo']}
******************** 已自动生成views ********************
/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/tyadmin_api_cli
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
auth Group Permission
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
user UserInfo Group
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
user UserInfo Permission
&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&
{'Permission': ['content_type$分割$ContentType'], 'Group': [], 'ContentType': [], 'UserInfo': []}
{'Permission': [], 'Group': ['permissions$分割$Permission'], 'ContentType': [], 'UserInfo': ['groups$分割$Group', 'user_permissions$分割$Permission']}
{'Permission': ['content_type$分割$ContentType'], 'Group': [], 'ContentType': [], 'UserInfo': []}
******************** 已自动生成serializers ********************
/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/tyadmin_api_cli
******************** 已自动生成filters ********************
/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/tyadmin_api_cli
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
auth
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
id
name
content_type
content_type
auth.Permission.content_type
codename
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/tyadmin_api_cli/management/commands/gen_all.py", line 38, in handle
    gen_all(setting_value, apps_list)
  File "/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/tyadmin_api_cli/init_filter_serial_url_view.py", line 18, in gen_all
    gen_antd_pages(project_name_settings, models_list)
  File "/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/venv/lib/python3.8/site-packages/tyadmin_api_cli/deal_antd_pages.py", line 912, in gen_antd_pages
    os.mkdir(cur_path)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/lin/Developer/python/cookiecutter-tyadmin-demo/TyadminDemo/tyadmin/src/pages/AutoGenPage/PermissionList'
```

**Comment by mtianyan** [comment]
@baikourin 试一下新版呢。这个问题已经解决了
